export const Envs = {
  app: {
    title: 'Any English',
    description: 'Generated by create next app',
  },
  api: {
    url: 'http://localhost:3000',
  },
  assets: {
    url: 'https://sv-cdn.netlify.app',
  },
};
